version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: tier_db_container
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
    networks:
      - backend
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: tier        
    container_name: tier
    ports:
      - 8080:8080
    volumes:
      - ./app:/src
    command: [sh, -c, npm install && npm start]
    networks:
      - backend
    depends_on:
      - mysql


networks:
  backend:

volumes:
  mysqldata: